---
title: "load_data"
output: html_document
date: "2024-09-21"
---

## Question 1

### Load data

```{r, warning=FALSE}
library(rmarkdown)
library(ggplot2)
library(readr)
library(tidyverse)
file_name <- list.files(path = "data/", pattern = "NYC_Dog_Licensing_Dataset_\\d+\\.csv", full.names = TRUE)
if (length(file_name) > 0) {
  data <- read.csv(file_name)
  print("File loaded successfully.")
} else {
  print("No matching file found.")
}
```
### Complete cases

```{r}
n_data = nrow(data)
complete_case <- data %>%
  mutate(across(everything(), ~str_replace_all(., "#VALUE!", NA_character_))) %>%
  rename(
    name = AnimalName, 
    gender = AnimalGender, 
    birth_year = AnimalBirthYear, 
    breed = BreedName, 
    zipcode = ZipCode, 
    issue_date = LicenseIssuedDate, 
    expiration_date = LicenseExpiredDate, 
    extract_year = Extract.Year
  ) %>% drop_na() %>%
  filter(
    name != "UNKNOWN" & name != "." & name != "NAME NOT PROVIDED"
    & name != "NONE" & name != "NAME"
  )
n_complete = nrow(complete_case)
cat(sprintf("Number of rows before filtering: %d\n", n_data))
cat(sprintf("Number of rows after filtering: %d\n", n_complete))
```
## Question 2

```{r}
distinct_case <- complete_case %>%
  distinct()
n_distinct = nrow(distinct_case)
cat(sprintf("Number of rows in complete cases: %d\n", n_complete))
cat(sprintf("Number of distinct rows in complete cases: %d\n", n_distinct))
```

```{r}
duplicate_case <- complete_case %>%
  group_by_all() %>%
  filter(n() > 1) %>%
  ungroup()
head(duplicate_case)
```
# Question 3

```{r}
distinct_case %>%
  group_by(birth_year) %>%
  summarize(count = n()) %>%
  arrange(birth_year) %>% 
  ggplot(aes(x = birth_year, y = count)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  labs(title = "Number of Dogs Born Each Year", x = "Year of Birth", y = "Number of Dogs") +
  theme_minimal() +
  #scale_x_continuous(limits = c(min_yr,max_yr)) +  
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) 
```
```{r}
threshold <- 1000
distinct_case %>%
  group_by(birth_year) %>%
  summarize(count = n()) %>%
  filter(count > threshold) %>%
  arrange(birth_year) %>% 
  ggplot(aes(x = birth_year, y = count)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  labs(title = "Number of Dogs Born Each Year: Count > 1000", x = "Year of Birth", y = "Number of Dogs") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) 
```
## Question 4

```{r}
unique_case <- distinct_case %>% 
  group_by(name, gender, birth_year, breed, zipcode) %>%
  slice(1) %>%
  ungroup()
n_unique <- nrow(unique_case)
cat(sprintf("Number of rows before the new rule: %d\n", n_distinct))
cat(sprintf("Number of rows after the new rule: %d\n", n_unique))
write.csv(unique_case, "data/unique_case.csv", row.names = FALSE)
```

